# Generated by Django 4.2.2 on 2023-06-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_basquetbolista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
